### ISSUE TITLE
multiple implementations of javax.activation.

### ISSUE THREAD

**Issue by Stexxen** [javaee/metro-jax-ws#1249]
I'm using JDK11 with rt version 2.4.0-b180810.0450

rt includes the following
```
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>javax.activation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.ws</groupId>
            <artifactId>policy</artifactId>
        </dependency>

```
com.sun.xml.ws.policy includes the following
```
        <dependency>
            <groupId>com.sun.activation</groupId>
            <artifactId>javax.activation</artifactId>
            <version>1.2.0</version>
        </dependency>

```

So rt has now included 2 different implementations of the package `javax.activation`

So now in `module-info.java` the line  
`requires java.activation; `

means there are 2 implementations to pick from.

I think the best approach is to remove the javax.activation package from com.sun.activation and add javax.activation-api as a dependancy.

**Comment by lukasj** [comment]
fixed in 2.3.2 in https://github.com/eclipse-ee4j/metro-jax-ws repo (there is going to be 'jakarta.activation' module)
