### ISSUE TITLE
Missing artifacts in maven central for 2.3.1

### ISSUE THREAD

**Issue by hazendaz** [javaee/metro-jax-ws#1252]
jaxws-tools-bundle (jar/source) 2.3.1 are missing from maven central.  I've tried manually buidling this project and it fails no matter what jdk used.  Can someone on this team get all artifacts released to central?

I do see other tickets open for jdk 11 support issues.  More specifically jaxws-maven-plugin doesn't work.  The first step to working I belive is getting the above modules released so the plugin will actually run.  Otherwise, one has to add jaxws-tools and exclude the bundle.  Doing so I believe completely breaks its use with jdk11 since it then cannot find the classes since the module path is missing.  I'm still new to understanding modules but suspect that is part of the issue.

**Comment by lukasj** [comment]
I can see it there: https://repo1.maven.org/maven2/com/sun/xml/ws/jaxws-tools/2.3.1/

**Comment by hazendaz** [comment]
The bundle module is the missing one.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lukasj** [comment]
https://repo1.maven.org/maven2/com/sun/xml/ws/bundles/2.3.1/ ? what groupid:artifactid exactly are you looking for?

**Comment by hazendaz** [comment]
Jaxws-tools-bundle.  The one with all the module info.  Attempts to use the maven plugin fail without it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
This is what is missing.  Both the jar and the source.  Maven fails on this even though it is listed as optional.  Subsequently, I'm having to list jaxws-rt directly and exclude this.  This module only has the module-info.java so I suspect it is key for jdk 11 usage to work with this plugin.

```xml
 <groupId>com.sun.xml.ws</groupId>
<artifactId>jaxws-rt-bundle</artifactId>
```

The artifact is not [here](https://search.maven.org/search?q=jaxws-rt-bundle)

**Comment by hazendaz** [comment]
@lukasj Can you please take another look here?  It seems not only here but in other modules with metro some artifacts are missing on latest releases additionally.  'jaxws-rt-bundle' is definitely not in central.  Both you have pointed to thus far are not the binary in question.  A maven build throws artifact not found in any repo as a result.
